from __future__ import annotations

SOURCE_TO_NORMALIZED = {
    "商品コード": "item_code",
    "商品名１": "item_name",
    "伝票日付": "transaction_date",
    "入出庫伝票№": "inventory_slip_no",
    "プログラム名": "program_name",
    "取引区分略称": "transaction_type",
    "ロット№": "lot_no",
    "入荷日": "receipt_date",
    "消費期限": "expiration_date",
    "フロアコード": "floor_code",
    "ロケーション№": "location_no",
    "単位名": "unit_name",
    "入庫数量": "qty_in",
    "出庫数量": "qty_out",
    "入数B": "pack_size_b",
    "入庫数（バラ）": "qty_in_each",
    "出庫数（バラ）": "qty_out_each",
    "ﾀｲﾑｽﾀﾝﾌﾟ（時間）": "event_time",
    "ﾀｲﾑｽﾀﾝﾌﾟ（日付）": "event_date",
    "担当者コード": "operator_code",
    "担当者名": "operator_name",
    "車番": "vehicle_no",
    "ﾃﾞｰﾀ・ﾀｲﾑｽﾀﾝﾌﾟ（日付）": "data_timestamp_date",
    "ﾃﾞｰﾀ･ﾀｲﾑｽﾀﾝﾌﾟ（時間）": "data_timestamp_time",
    "タイムスタンプ2桁": "timestamp_2digit",
    "タイムスタンプ4桁": "timestamp_4digit",
    "社内備考": "internal_notes",
    "備考": "remarks",
    "クライアントＩＤ": "client_id",
    "最終作業者コード": "last_operator_code",
}

CORE_FIELDS = {
    "item_code",
    "transaction_date",
    "inventory_slip_no",
    "transaction_type",
    "lot_no",
    "expiration_date",
    "location_no",
    "unit_name",
    "qty_in",
    "qty_out",
    "event_date",
    "event_time",
    "operator_code",
    "client_id",
}
